language: go

go:
  - '1.12'

matrix:
  include:
    - os: windows
      env:
        - TEST_DIR='cli'
    - os: windows
      env:
        - TEST_DIR='spliced'

install:
  - go get -v ./$TEST_DIR/...

script:
  - go test -v ./$TEST_DIR/...
